
# This file is automatically generated, you probably don't want to edit this

mpcontOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mpcontOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            studyLabel = NULL,
            meanE = NULL,
            sdE = NULL,
            nE = NULL,
            meanC = NULL,
            sdC = NULL,
            nC = NULL,
            sm = "md",
            methodSmd = "hedges",
            random = TRUE,
            common = TRUE,
            methodTau = "reml",
            prediction = FALSE,
            confidenceLevel = 0.95,
            groupLabelE = "Experimental",
            groupLabelC = "Control",
            LOO = FALSE,
            OUT = FALSE,
            baujat = FALSE,
            InfluenceCharacteristics = FALSE,
            ForestEffectSize = FALSE,
            ForestI2 = FALSE, ...) {

            super$initialize(
                package="MetaPort",
                name="mpcont",
                requiresData=TRUE,
                ...)

            private$..studyLabel <- jmvcore::OptionVariable$new(
                "studyLabel",
                studyLabel,
                suggested=list(
                    "nominal",
                    "ordinal",
                    "id"))
            private$..meanE <- jmvcore::OptionVariable$new(
                "meanE",
                meanE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sdE <- jmvcore::OptionVariable$new(
                "sdE",
                sdE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..nE <- jmvcore::OptionVariable$new(
                "nE",
                nE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..meanC <- jmvcore::OptionVariable$new(
                "meanC",
                meanC,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sdC <- jmvcore::OptionVariable$new(
                "sdC",
                sdC,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..nC <- jmvcore::OptionVariable$new(
                "nC",
                nC,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sm <- jmvcore::OptionList$new(
                "sm",
                sm,
                options=list(
                    "md",
                    "smd",
                    "rom"),
                default="md")
            private$..methodSmd <- jmvcore::OptionList$new(
                "methodSmd",
                methodSmd,
                options=list(
                    "hedges",
                    "cohen",
                    "glass"),
                default="hedges")
            private$..random <- jmvcore::OptionBool$new(
                "random",
                random,
                default=TRUE)
            private$..common <- jmvcore::OptionBool$new(
                "common",
                common,
                default=TRUE)
            private$..methodTau <- jmvcore::OptionList$new(
                "methodTau",
                methodTau,
                options=list(
                    "reml",
                    "dl",
                    "pm",
                    "ml",
                    "hs",
                    "sj",
                    "he",
                    "eb"),
                default="reml")
            private$..prediction <- jmvcore::OptionBool$new(
                "prediction",
                prediction,
                default=FALSE)
            private$..confidenceLevel <- jmvcore::OptionNumber$new(
                "confidenceLevel",
                confidenceLevel,
                default=0.95)
            private$..groupLabelE <- jmvcore::OptionString$new(
                "groupLabelE",
                groupLabelE,
                default="Experimental")
            private$..groupLabelC <- jmvcore::OptionString$new(
                "groupLabelC",
                groupLabelC,
                default="Control")
            private$..LOO <- jmvcore::OptionBool$new(
                "LOO",
                LOO,
                default=FALSE)
            private$..OUT <- jmvcore::OptionBool$new(
                "OUT",
                OUT,
                default=FALSE)
            private$..baujat <- jmvcore::OptionBool$new(
                "baujat",
                baujat,
                default=FALSE)
            private$..InfluenceCharacteristics <- jmvcore::OptionBool$new(
                "InfluenceCharacteristics",
                InfluenceCharacteristics,
                default=FALSE)
            private$..ForestEffectSize <- jmvcore::OptionBool$new(
                "ForestEffectSize",
                ForestEffectSize,
                default=FALSE)
            private$..ForestI2 <- jmvcore::OptionBool$new(
                "ForestI2",
                ForestI2,
                default=FALSE)

            self$.addOption(private$..studyLabel)
            self$.addOption(private$..meanE)
            self$.addOption(private$..sdE)
            self$.addOption(private$..nE)
            self$.addOption(private$..meanC)
            self$.addOption(private$..sdC)
            self$.addOption(private$..nC)
            self$.addOption(private$..sm)
            self$.addOption(private$..methodSmd)
            self$.addOption(private$..random)
            self$.addOption(private$..common)
            self$.addOption(private$..methodTau)
            self$.addOption(private$..prediction)
            self$.addOption(private$..confidenceLevel)
            self$.addOption(private$..groupLabelE)
            self$.addOption(private$..groupLabelC)
            self$.addOption(private$..LOO)
            self$.addOption(private$..OUT)
            self$.addOption(private$..baujat)
            self$.addOption(private$..InfluenceCharacteristics)
            self$.addOption(private$..ForestEffectSize)
            self$.addOption(private$..ForestI2)
        }),
    active = list(
        studyLabel = function() private$..studyLabel$value,
        meanE = function() private$..meanE$value,
        sdE = function() private$..sdE$value,
        nE = function() private$..nE$value,
        meanC = function() private$..meanC$value,
        sdC = function() private$..sdC$value,
        nC = function() private$..nC$value,
        sm = function() private$..sm$value,
        methodSmd = function() private$..methodSmd$value,
        random = function() private$..random$value,
        common = function() private$..common$value,
        methodTau = function() private$..methodTau$value,
        prediction = function() private$..prediction$value,
        confidenceLevel = function() private$..confidenceLevel$value,
        groupLabelE = function() private$..groupLabelE$value,
        groupLabelC = function() private$..groupLabelC$value,
        LOO = function() private$..LOO$value,
        OUT = function() private$..OUT$value,
        baujat = function() private$..baujat$value,
        InfluenceCharacteristics = function() private$..InfluenceCharacteristics$value,
        ForestEffectSize = function() private$..ForestEffectSize$value,
        ForestI2 = function() private$..ForestI2$value),
    private = list(
        ..studyLabel = NA,
        ..meanE = NA,
        ..sdE = NA,
        ..nE = NA,
        ..meanC = NA,
        ..sdC = NA,
        ..nC = NA,
        ..sm = NA,
        ..methodSmd = NA,
        ..random = NA,
        ..common = NA,
        ..methodTau = NA,
        ..prediction = NA,
        ..confidenceLevel = NA,
        ..groupLabelE = NA,
        ..groupLabelC = NA,
        ..LOO = NA,
        ..OUT = NA,
        ..baujat = NA,
        ..InfluenceCharacteristics = NA,
        ..ForestEffectSize = NA,
        ..ForestI2 = NA)
)

mpcontResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mpcontResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        plot = function() private$.items[["plot"]],
        LOOText = function() private$.items[["LOOText"]],
        LOOPlot = function() private$.items[["LOOPlot"]],
        OUTText = function() private$.items[["OUTText"]],
        OUTPlot = function() private$.items[["OUTPlot"]],
        infText = function() private$.items[["infText"]],
        baujatPlot = function() private$.items[["baujatPlot"]],
        infPlot = function() private$.items[["infPlot"]],
        ForestEffectSizePlot = function() private$.items[["ForestEffectSizePlot"]],
        ForestI2Plot = function() private$.items[["ForestI2Plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Meta-analysis of continuous outcome data")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Results for Overall meta analysis",
                clearWith=list(
                    "meanE",
                    "sdE",
                    "nE",
                    "meanC",
                    "sdC",
                    "nC",
                    "studyLabel",
                    "groupLabelE",
                    "groupLabelC",
                    "sm",
                    "methodTau",
                    "methodSmd",
                    "random",
                    "common",
                    "prediction",
                    "confidenceLevel"),
                refs=list(
                    "metaPackage")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Forest Plot",
                width=800,
                height=1000,
                renderFun=".forestPlot",
                clearWith=list(
                    "meanE",
                    "sdE",
                    "nE",
                    "meanC",
                    "sdC",
                    "nC",
                    "studyLabel",
                    "groupLabelE",
                    "groupLabelC",
                    "sm",
                    "methodTau",
                    "methodSmd",
                    "random",
                    "common",
                    "prediction",
                    "confidenceLevel"),
                refs=list(
                    "metaPackage")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="LOOText",
                title="leave-one-out Analysis",
                clearWith=list(
                    "meanE",
                    "sdE",
                    "nE",
                    "meanC",
                    "sdC",
                    "nC",
                    "studyLabel",
                    "groupLabelE",
                    "groupLabelC",
                    "sm",
                    "methodTau",
                    "methodSmd",
                    "random",
                    "common",
                    "confidenceLevel"),
                refs=list(
                    "metaPackage")))
            self$add(jmvcore::Image$new(
                options=options,
                name="LOOPlot",
                title="leave-one-out Plot",
                width=800,
                height=1000,
                renderFun=".LOOPlot",
                clearWith=list(
                    "meanE",
                    "sdE",
                    "nE",
                    "meanC",
                    "sdC",
                    "nC",
                    "studyLabel",
                    "groupLabelE",
                    "groupLabelC",
                    "sm",
                    "methodTau",
                    "methodSmd",
                    "random",
                    "common",
                    "confidenceLevel"),
                refs=list(
                    "metaPackage")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="OUTText",
                title="Outliers Analysis",
                clearWith=list(
                    "meanE",
                    "sdE",
                    "nE",
                    "meanC",
                    "sdC",
                    "nC",
                    "studyLabel",
                    "groupLabelE",
                    "groupLabelC",
                    "sm",
                    "methodTau",
                    "methodSmd",
                    "random",
                    "common",
                    "confidenceLevel"),
                refs=list(
                    "dmetarPackage",
                    "metaPackage")))
            self$add(jmvcore::Image$new(
                options=options,
                name="OUTPlot",
                title="Outliers Plot",
                width=800,
                height=1000,
                renderFun=".OUTPlot",
                clearWith=list(
                    "meanE",
                    "sdE",
                    "nE",
                    "meanC",
                    "sdC",
                    "nC",
                    "studyLabel",
                    "groupLabelE",
                    "groupLabelC",
                    "sm",
                    "methodTau",
                    "methodSmd",
                    "random",
                    "common",
                    "confidenceLevel"),
                refs=list(
                    "dmetarPackage",
                    "metaPackage")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="infText",
                title="Influence Analysis",
                clearWith=list(
                    "meanE",
                    "sdE",
                    "nE",
                    "meanC",
                    "sdC",
                    "nC",
                    "studyLabel",
                    "groupLabelE",
                    "groupLabelC",
                    "sm",
                    "methodTau",
                    "methodSmd",
                    "random",
                    "common",
                    "confidenceLevel"),
                refs=list(
                    "dmetarPackage")))
            self$add(jmvcore::Image$new(
                options=options,
                name="baujatPlot",
                title="baujat Plot",
                width=800,
                height=1000,
                renderFun=".baujatPlot",
                clearWith=list(
                    "meanE",
                    "sdE",
                    "nE",
                    "meanC",
                    "sdC",
                    "nC",
                    "studyLabel",
                    "groupLabelE",
                    "groupLabelC",
                    "sm",
                    "methodTau",
                    "methodSmd",
                    "random",
                    "common",
                    "confidenceLevel"),
                refs=list(
                    "dmetarPackage")))
            self$add(jmvcore::Image$new(
                options=options,
                name="infPlot",
                title="Influence Characteristics Plot",
                width=800,
                height=1000,
                renderFun=".infPlot",
                clearWith=list(
                    "meanE",
                    "sdE",
                    "nE",
                    "meanC",
                    "sdC",
                    "nC",
                    "studyLabel",
                    "groupLabelE",
                    "groupLabelC",
                    "sm",
                    "methodTau",
                    "methodSmd",
                    "random",
                    "common",
                    "confidenceLevel"),
                refs=list(
                    "dmetarPackage")))
            self$add(jmvcore::Image$new(
                options=options,
                name="ForestEffectSizePlot",
                title="Forest Plot Sorted By Effect Size",
                width=800,
                height=1000,
                renderFun=".ForestEffectSizePlot",
                clearWith=list(
                    "meanE",
                    "sdE",
                    "nE",
                    "meanC",
                    "sdC",
                    "nC",
                    "studyLabel",
                    "groupLabelE",
                    "groupLabelC",
                    "sm",
                    "methodTau",
                    "methodSmd",
                    "random",
                    "common",
                    "confidenceLevel"),
                refs=list(
                    "dmetarPackage")))
            self$add(jmvcore::Image$new(
                options=options,
                name="ForestI2Plot",
                title="Forest Plot Sorted By between-study heterogeneity",
                width=800,
                height=1000,
                renderFun=".ForestI2Plot",
                clearWith=list(
                    "meanE",
                    "sdE",
                    "nE",
                    "meanC",
                    "sdC",
                    "nC",
                    "studyLabel",
                    "groupLabelE",
                    "groupLabelC",
                    "sm",
                    "methodTau",
                    "methodSmd",
                    "random",
                    "common",
                    "confidenceLevel"),
                refs=list(
                    "dmetarPackage")))}))

mpcontBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mpcontBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "MetaPort",
                name = "mpcont",
                version = c(1,0,0),
                options = options,
                results = mpcontResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Meta-analysis of continuous outcome data
#'
#' 
#' @param data .
#' @param studyLabel .
#' @param meanE .
#' @param sdE .
#' @param nE .
#' @param meanC .
#' @param sdC .
#' @param nC .
#' @param sm .
#' @param methodSmd .
#' @param random .
#' @param common .
#' @param methodTau .
#' @param prediction .
#' @param confidenceLevel .
#' @param groupLabelE .
#' @param groupLabelC .
#' @param LOO .
#' @param OUT .
#' @param baujat .
#' @param InfluenceCharacteristics .
#' @param ForestEffectSize .
#' @param ForestI2 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$LOOText} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$LOOPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$OUTText} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$OUTPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$infText} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$baujatPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$infPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$ForestEffectSizePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$ForestI2Plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
mpcont <- function(
    data,
    studyLabel,
    meanE,
    sdE,
    nE,
    meanC,
    sdC,
    nC,
    sm = "md",
    methodSmd = "hedges",
    random = TRUE,
    common = TRUE,
    methodTau = "reml",
    prediction = FALSE,
    confidenceLevel = 0.95,
    groupLabelE = "Experimental",
    groupLabelC = "Control",
    LOO = FALSE,
    OUT = FALSE,
    baujat = FALSE,
    InfluenceCharacteristics = FALSE,
    ForestEffectSize = FALSE,
    ForestI2 = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mpcont requires jmvcore to be installed (restart may be required)")

    if ( ! missing(studyLabel)) studyLabel <- jmvcore::resolveQuo(jmvcore::enquo(studyLabel))
    if ( ! missing(meanE)) meanE <- jmvcore::resolveQuo(jmvcore::enquo(meanE))
    if ( ! missing(sdE)) sdE <- jmvcore::resolveQuo(jmvcore::enquo(sdE))
    if ( ! missing(nE)) nE <- jmvcore::resolveQuo(jmvcore::enquo(nE))
    if ( ! missing(meanC)) meanC <- jmvcore::resolveQuo(jmvcore::enquo(meanC))
    if ( ! missing(sdC)) sdC <- jmvcore::resolveQuo(jmvcore::enquo(sdC))
    if ( ! missing(nC)) nC <- jmvcore::resolveQuo(jmvcore::enquo(nC))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(studyLabel), studyLabel, NULL),
            `if`( ! missing(meanE), meanE, NULL),
            `if`( ! missing(sdE), sdE, NULL),
            `if`( ! missing(nE), nE, NULL),
            `if`( ! missing(meanC), meanC, NULL),
            `if`( ! missing(sdC), sdC, NULL),
            `if`( ! missing(nC), nC, NULL))


    options <- mpcontOptions$new(
        studyLabel = studyLabel,
        meanE = meanE,
        sdE = sdE,
        nE = nE,
        meanC = meanC,
        sdC = sdC,
        nC = nC,
        sm = sm,
        methodSmd = methodSmd,
        random = random,
        common = common,
        methodTau = methodTau,
        prediction = prediction,
        confidenceLevel = confidenceLevel,
        groupLabelE = groupLabelE,
        groupLabelC = groupLabelC,
        LOO = LOO,
        OUT = OUT,
        baujat = baujat,
        InfluenceCharacteristics = InfluenceCharacteristics,
        ForestEffectSize = ForestEffectSize,
        ForestI2 = ForestI2)

    analysis <- mpcontClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

